language: php

php:
  - 7.1
  - 7.2
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

sudo: false

before_script:
  - composer update --dev

script: phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls -v